Add home page functionality
mattc0d3/nc-news-fe pull request #2
Opened 2023-07-17 15:27 UTC by mattc0d3

2023-07-17 15:45 UTC, NRMSMITH requested changes
Your design is really responsive which is lovely - what I would suggest is that you need to have a loading state created. I would also suggest having your apicalls in one file :) Please submit another PR when you have completed this tomorrow morning :) (not during the lecture!!)

2023-07-17 15:45 UTC, NRMSMITH commented on src/utils/getTopics.js
> +const getTopics = () => {
I would suggest that this doesn't need to be in a different file - you could just have a single apicalls file :)

2023-07-17 15:45 UTC, NRMSMITH commented on src/components/Home.jsx
> +
an isLoading state would be really beneficial here

2023-07-18 09:03 UTC, itskatherine reviewed
Love the pagination Matt - a few comments to look over but once you have you're good to merge 👍

2023-07-18 09:03 UTC, itskatherine commented on src/utils/apis.js
> +    return api.get(`/articles?p=${resultsPage}&total_count=true`).then(res => res.data)
Nice that you've split out this functionality into an api file ⭐  - you might want to consider using the [axios params object](https://notes.northcoders.com/courses/js-front-end/axios#axios-params), to save using a template literal here, up to you though!

2023-07-18 09:03 UTC, itskatherine commented on src/components/SearchBar.jsx
> +    </section>
Though this is good to add, I would say that this element (though it isn't working yet) isn't in the scope of this ticket/task (it is in the scope of some tickets further on) - and it's important in PRs for the code just to meet the requirements of that ticket. Going forward try to keep this in mind 🧠

2023-07-18 09:18 UTC, merged